spring:
  application:
    name: back-manager
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
server:
  port: 8766
  session:
    timeout: 1
eureka:
  instance:
    appname: back-manager
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true